artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source: iabhishekofficial/mobile-price-classification
  local_data_file: artifacts/data/raw

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['train.csv'] # We can add test.csv too.