artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source: iabhishekofficial/mobile-price-classification
  local_data_file: artifacts/data/raw

data_validation:
  root_dir: artifacts/data
  STATUS_FILE: artifacts/data/validation_status.txt
  ALL_REQUIRED_FILES: ['train.csv'] # We can add test.csv too.

data_transformation:
  root_dir: artifacts/data
  raw_data_path: artifacts/data/raw
  validation_status: artifacts/data/validation_status.txt
  local_data_file: artifacts/data/processed

model_trainer: 
  root_dir: artifacts/model
  data_path: artifacts/data/processed 

model_evaluation:
  root_dir: artifacts/model
  data_path: artifacts/data/processed 
  model_path: artifacts/model
  metric_file_name: artifacts/model/metrics.csv
